import type { Metadata } from 'next'
import React from 'react'

// import { Toaster } from '@/components/ui/toaster'
import { Toaster } from '@/components/ui/sonner'
import { fontSans, fontItaliana } from '@/lib/fonts'
import { cn } from '@/lib/utils'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen relative bg-background text-foreground font-sans antialiased',
          fontSans.variable,
          fontItaliana.variable
        )}
        suppressHydrationWarning
      >
        {children}
        <Toaster position='bottom-right' richColors />
      </body>
    </html>
  )
}